/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BetaFechadoRouteImport } from './routes/beta-fechado'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as PainelAdminAcessosRouteImport } from './routes/painel.admin-acessos'
import { Route as PainelAgendaRouteImport } from './routes/painel.agenda'
import { Route as PainelClientesRouteImport } from './routes/painel.clientes'
import { Route as PainelConfiguracoesRouteImport } from './routes/painel.configuracoes'
import { Route as PainelEmpresaRouteImport } from './routes/painel.empresa'
import { Route as PainelEstoqueRouteImport } from './routes/painel.estoque'
import { Route as PainelFinanceiroRouteImport } from './routes/painel.financeiro'
import { Route as PainelMarketingRouteImport } from './routes/painel.marketing'
import { Route as PainelPaginaPublicaRouteImport } from './routes/painel.pagina-publica'
import { Route as PainelProdutosRouteImport } from './routes/painel.produtos'
import { Route as PainelProfissionaisRouteImport } from './routes/painel.profissionais'
import { Route as PainelRelatoriosRouteImport } from './routes/painel.relatorios'
import { Route as PainelServicosRouteImport } from './routes/painel.servicos'
import { Route as ApiMercadoPagoWebhookRouteImport } from './routes/api.mercado-pago.webhook'
import { Route as IntegracoesMercadoPagoRetornoRouteImport } from './routes/integracoes.mercado-pago.retorno'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaFechadoRoute = BetaFechadoRouteImport.update({
  id: '/beta-fechado',
  path: '/beta-fechado',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelAdminAcessosRoute = PainelAdminAcessosRouteImport.update({
  id: '/admin-acessos',
  path: '/admin-acessos',
  getParentRoute: () => PainelRoute,
} as any)
const PainelAgendaRoute = PainelAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => PainelRoute,
} as any)
const PainelClientesRoute = PainelClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelConfiguracoesRoute = PainelConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelEmpresaRoute = PainelEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => PainelRoute,
} as any)
const PainelEstoqueRoute = PainelEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => PainelRoute,
} as any)
const PainelFinanceiroRoute = PainelFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => PainelRoute,
} as any)
const PainelMarketingRoute = PainelMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => PainelRoute,
} as any)
const PainelPaginaPublicaRoute = PainelPaginaPublicaRouteImport.update({
  id: '/pagina-publica',
  path: '/pagina-publica',
  getParentRoute: () => PainelRoute,
} as any)
const PainelProdutosRoute = PainelProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => PainelRoute,
} as any)
const PainelProfissionaisRoute = PainelProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => PainelRoute,
} as any)
const PainelRelatoriosRoute = PainelRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => PainelRoute,
} as any)
const PainelServicosRoute = PainelServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => PainelRoute,
} as any)
const ApiMercadoPagoWebhookRoute = ApiMercadoPagoWebhookRouteImport.update({
  id: '/api/mercado-pago/webhook',
  path: '/api/mercado-pago/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesMercadoPagoRetornoRoute =
  IntegracoesMercadoPagoRetornoRouteImport.update({
    id: '/integracoes/mercado-pago/retorno',
    path: '/integracoes/mercado-pago/retorno',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beta-fechado': typeof BetaFechadoRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/painel': typeof PainelRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/p/$slug': typeof PSlugRoute
  '/painel/admin-acessos': typeof PainelAdminAcessosRoute
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/clientes': typeof PainelClientesRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/empresa': typeof PainelEmpresaRoute
  '/painel/estoque': typeof PainelEstoqueRoute
  '/painel/financeiro': typeof PainelFinanceiroRoute
  '/painel/marketing': typeof PainelMarketingRoute
  '/painel/pagina-publica': typeof PainelPaginaPublicaRoute
  '/painel/produtos': typeof PainelProdutosRoute
  '/painel/profissionais': typeof PainelProfissionaisRoute
  '/painel/relatorios': typeof PainelRelatoriosRoute
  '/painel/servicos': typeof PainelServicosRoute
  '/painel/': typeof PainelIndexRoute
  '/api/mercado-pago/webhook': typeof ApiMercadoPagoWebhookRoute
  '/integracoes/mercado-pago/retorno': typeof IntegracoesMercadoPagoRetornoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beta-fechado': typeof BetaFechadoRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/p/$slug': typeof PSlugRoute
  '/painel/admin-acessos': typeof PainelAdminAcessosRoute
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/clientes': typeof PainelClientesRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/empresa': typeof PainelEmpresaRoute
  '/painel/estoque': typeof PainelEstoqueRoute
  '/painel/financeiro': typeof PainelFinanceiroRoute
  '/painel/marketing': typeof PainelMarketingRoute
  '/painel/pagina-publica': typeof PainelPaginaPublicaRoute
  '/painel/produtos': typeof PainelProdutosRoute
  '/painel/profissionais': typeof PainelProfissionaisRoute
  '/painel/relatorios': typeof PainelRelatoriosRoute
  '/painel/servicos': typeof PainelServicosRoute
  '/painel': typeof PainelIndexRoute
  '/api/mercado-pago/webhook': typeof ApiMercadoPagoWebhookRoute
  '/integracoes/mercado-pago/retorno': typeof IntegracoesMercadoPagoRetornoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beta-fechado': typeof BetaFechadoRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/painel': typeof PainelRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/p/$slug': typeof PSlugRoute
  '/painel/admin-acessos': typeof PainelAdminAcessosRoute
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/clientes': typeof PainelClientesRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/empresa': typeof PainelEmpresaRoute
  '/painel/estoque': typeof PainelEstoqueRoute
  '/painel/financeiro': typeof PainelFinanceiroRoute
  '/painel/marketing': typeof PainelMarketingRoute
  '/painel/pagina-publica': typeof PainelPaginaPublicaRoute
  '/painel/produtos': typeof PainelProdutosRoute
  '/painel/profissionais': typeof PainelProfissionaisRoute
  '/painel/relatorios': typeof PainelRelatoriosRoute
  '/painel/servicos': typeof PainelServicosRoute
  '/painel/': typeof PainelIndexRoute
  '/api/mercado-pago/webhook': typeof ApiMercadoPagoWebhookRoute
  '/integracoes/mercado-pago/retorno': typeof IntegracoesMercadoPagoRetornoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beta-fechado'
    | '/cadastro'
    | '/login'
    | '/onboarding'
    | '/painel'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/auth/confirm'
    | '/p/$slug'
    | '/painel/admin-acessos'
    | '/painel/agenda'
    | '/painel/clientes'
    | '/painel/configuracoes'
    | '/painel/empresa'
    | '/painel/estoque'
    | '/painel/financeiro'
    | '/painel/marketing'
    | '/painel/pagina-publica'
    | '/painel/produtos'
    | '/painel/profissionais'
    | '/painel/relatorios'
    | '/painel/servicos'
    | '/painel/'
    | '/api/mercado-pago/webhook'
    | '/integracoes/mercado-pago/retorno'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beta-fechado'
    | '/cadastro'
    | '/login'
    | '/onboarding'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/auth/confirm'
    | '/p/$slug'
    | '/painel/admin-acessos'
    | '/painel/agenda'
    | '/painel/clientes'
    | '/painel/configuracoes'
    | '/painel/empresa'
    | '/painel/estoque'
    | '/painel/financeiro'
    | '/painel/marketing'
    | '/painel/pagina-publica'
    | '/painel/produtos'
    | '/painel/profissionais'
    | '/painel/relatorios'
    | '/painel/servicos'
    | '/painel'
    | '/api/mercado-pago/webhook'
    | '/integracoes/mercado-pago/retorno'
  id:
    | '__root__'
    | '/'
    | '/beta-fechado'
    | '/cadastro'
    | '/login'
    | '/onboarding'
    | '/painel'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/auth/confirm'
    | '/p/$slug'
    | '/painel/admin-acessos'
    | '/painel/agenda'
    | '/painel/clientes'
    | '/painel/configuracoes'
    | '/painel/empresa'
    | '/painel/estoque'
    | '/painel/financeiro'
    | '/painel/marketing'
    | '/painel/pagina-publica'
    | '/painel/produtos'
    | '/painel/profissionais'
    | '/painel/relatorios'
    | '/painel/servicos'
    | '/painel/'
    | '/api/mercado-pago/webhook'
    | '/integracoes/mercado-pago/retorno'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BetaFechadoRoute: typeof BetaFechadoRoute
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PainelRoute: typeof PainelRouteWithChildren
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  PSlugRoute: typeof PSlugRoute
  ApiMercadoPagoWebhookRoute: typeof ApiMercadoPagoWebhookRoute
  IntegracoesMercadoPagoRetornoRoute: typeof IntegracoesMercadoPagoRetornoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta-fechado': {
      id: '/beta-fechado'
      path: '/beta-fechado'
      fullPath: '/beta-fechado'
      preLoaderRoute: typeof BetaFechadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/admin-acessos': {
      id: '/painel/admin-acessos'
      path: '/admin-acessos'
      fullPath: '/painel/admin-acessos'
      preLoaderRoute: typeof PainelAdminAcessosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/agenda': {
      id: '/painel/agenda'
      path: '/agenda'
      fullPath: '/painel/agenda'
      preLoaderRoute: typeof PainelAgendaRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/clientes': {
      id: '/painel/clientes'
      path: '/clientes'
      fullPath: '/painel/clientes'
      preLoaderRoute: typeof PainelClientesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/configuracoes': {
      id: '/painel/configuracoes'
      path: '/configuracoes'
      fullPath: '/painel/configuracoes'
      preLoaderRoute: typeof PainelConfiguracoesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/empresa': {
      id: '/painel/empresa'
      path: '/empresa'
      fullPath: '/painel/empresa'
      preLoaderRoute: typeof PainelEmpresaRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/estoque': {
      id: '/painel/estoque'
      path: '/estoque'
      fullPath: '/painel/estoque'
      preLoaderRoute: typeof PainelEstoqueRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/financeiro': {
      id: '/painel/financeiro'
      path: '/financeiro'
      fullPath: '/painel/financeiro'
      preLoaderRoute: typeof PainelFinanceiroRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/marketing': {
      id: '/painel/marketing'
      path: '/marketing'
      fullPath: '/painel/marketing'
      preLoaderRoute: typeof PainelMarketingRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/pagina-publica': {
      id: '/painel/pagina-publica'
      path: '/pagina-publica'
      fullPath: '/painel/pagina-publica'
      preLoaderRoute: typeof PainelPaginaPublicaRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/produtos': {
      id: '/painel/produtos'
      path: '/produtos'
      fullPath: '/painel/produtos'
      preLoaderRoute: typeof PainelProdutosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/profissionais': {
      id: '/painel/profissionais'
      path: '/profissionais'
      fullPath: '/painel/profissionais'
      preLoaderRoute: typeof PainelProfissionaisRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/relatorios': {
      id: '/painel/relatorios'
      path: '/relatorios'
      fullPath: '/painel/relatorios'
      preLoaderRoute: typeof PainelRelatoriosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/servicos': {
      id: '/painel/servicos'
      path: '/servicos'
      fullPath: '/painel/servicos'
      preLoaderRoute: typeof PainelServicosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/api/mercado-pago/webhook': {
      id: '/api/mercado-pago/webhook'
      path: '/api/mercado-pago/webhook'
      fullPath: '/api/mercado-pago/webhook'
      preLoaderRoute: typeof ApiMercadoPagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes/mercado-pago/retorno': {
      id: '/integracoes/mercado-pago/retorno'
      path: '/integracoes/mercado-pago/retorno'
      fullPath: '/integracoes/mercado-pago/retorno'
      preLoaderRoute: typeof IntegracoesMercadoPagoRetornoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PainelRouteChildren {
  PainelAdminAcessosRoute: typeof PainelAdminAcessosRoute
  PainelAgendaRoute: typeof PainelAgendaRoute
  PainelClientesRoute: typeof PainelClientesRoute
  PainelConfiguracoesRoute: typeof PainelConfiguracoesRoute
  PainelEmpresaRoute: typeof PainelEmpresaRoute
  PainelEstoqueRoute: typeof PainelEstoqueRoute
  PainelFinanceiroRoute: typeof PainelFinanceiroRoute
  PainelMarketingRoute: typeof PainelMarketingRoute
  PainelPaginaPublicaRoute: typeof PainelPaginaPublicaRoute
  PainelProdutosRoute: typeof PainelProdutosRoute
  PainelProfissionaisRoute: typeof PainelProfissionaisRoute
  PainelRelatoriosRoute: typeof PainelRelatoriosRoute
  PainelServicosRoute: typeof PainelServicosRoute
  PainelIndexRoute: typeof PainelIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelAdminAcessosRoute: PainelAdminAcessosRoute,
  PainelAgendaRoute: PainelAgendaRoute,
  PainelClientesRoute: PainelClientesRoute,
  PainelConfiguracoesRoute: PainelConfiguracoesRoute,
  PainelEmpresaRoute: PainelEmpresaRoute,
  PainelEstoqueRoute: PainelEstoqueRoute,
  PainelFinanceiroRoute: PainelFinanceiroRoute,
  PainelMarketingRoute: PainelMarketingRoute,
  PainelPaginaPublicaRoute: PainelPaginaPublicaRoute,
  PainelProdutosRoute: PainelProdutosRoute,
  PainelProfissionaisRoute: PainelProfissionaisRoute,
  PainelRelatoriosRoute: PainelRelatoriosRoute,
  PainelServicosRoute: PainelServicosRoute,
  PainelIndexRoute: PainelIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BetaFechadoRoute: BetaFechadoRoute,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PainelRoute: PainelRouteWithChildren,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  PSlugRoute: PSlugRoute,
  ApiMercadoPagoWebhookRoute: ApiMercadoPagoWebhookRoute,
  IntegracoesMercadoPagoRetornoRoute: IntegracoesMercadoPagoRetornoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
