/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as PainelAgendaRouteImport } from './routes/painel.agenda'
import { Route as PainelClientesRouteImport } from './routes/painel.clientes'
import { Route as PainelConfiguracoesRouteImport } from './routes/painel.configuracoes'
import { Route as PainelEstoqueRouteImport } from './routes/painel.estoque'
import { Route as PainelFinanceiroRouteImport } from './routes/painel.financeiro'
import { Route as PainelGaleriaRouteImport } from './routes/painel.galeria'
import { Route as PainelMarketingRouteImport } from './routes/painel.marketing'
import { Route as PainelServicosRouteImport } from './routes/painel.servicos'
import { Route as ServicoIdRouteImport } from './routes/servico.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelAgendaRoute = PainelAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => PainelRoute,
} as any)
const PainelClientesRoute = PainelClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelConfiguracoesRoute = PainelConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelEstoqueRoute = PainelEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => PainelRoute,
} as any)
const PainelFinanceiroRoute = PainelFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => PainelRoute,
} as any)
const PainelGaleriaRoute = PainelGaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => PainelRoute,
} as any)
const PainelMarketingRoute = PainelMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => PainelRoute,
} as any)
const PainelServicosRoute = PainelServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => PainelRoute,
} as any)
const ServicoIdRoute = ServicoIdRouteImport.update({
  id: '/servico/$id',
  path: '/servico/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/painel': typeof PainelRouteWithChildren
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/clientes': typeof PainelClientesRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/estoque': typeof PainelEstoqueRoute
  '/painel/financeiro': typeof PainelFinanceiroRoute
  '/painel/galeria': typeof PainelGaleriaRoute
  '/painel/marketing': typeof PainelMarketingRoute
  '/painel/servicos': typeof PainelServicosRoute
  '/servico/$id': typeof ServicoIdRoute
  '/painel/': typeof PainelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/clientes': typeof PainelClientesRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/estoque': typeof PainelEstoqueRoute
  '/painel/financeiro': typeof PainelFinanceiroRoute
  '/painel/galeria': typeof PainelGaleriaRoute
  '/painel/marketing': typeof PainelMarketingRoute
  '/painel/servicos': typeof PainelServicosRoute
  '/servico/$id': typeof ServicoIdRoute
  '/painel': typeof PainelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/painel': typeof PainelRouteWithChildren
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/clientes': typeof PainelClientesRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/estoque': typeof PainelEstoqueRoute
  '/painel/financeiro': typeof PainelFinanceiroRoute
  '/painel/galeria': typeof PainelGaleriaRoute
  '/painel/marketing': typeof PainelMarketingRoute
  '/painel/servicos': typeof PainelServicosRoute
  '/servico/$id': typeof ServicoIdRoute
  '/painel/': typeof PainelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar'
    | '/painel'
    | '/painel/agenda'
    | '/painel/clientes'
    | '/painel/configuracoes'
    | '/painel/estoque'
    | '/painel/financeiro'
    | '/painel/galeria'
    | '/painel/marketing'
    | '/painel/servicos'
    | '/servico/$id'
    | '/painel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/painel/agenda'
    | '/painel/clientes'
    | '/painel/configuracoes'
    | '/painel/estoque'
    | '/painel/financeiro'
    | '/painel/galeria'
    | '/painel/marketing'
    | '/painel/servicos'
    | '/servico/$id'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/agendar'
    | '/painel'
    | '/painel/agenda'
    | '/painel/clientes'
    | '/painel/configuracoes'
    | '/painel/estoque'
    | '/painel/financeiro'
    | '/painel/galeria'
    | '/painel/marketing'
    | '/painel/servicos'
    | '/servico/$id'
    | '/painel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendarRoute: typeof AgendarRoute
  PainelRoute: typeof PainelRouteWithChildren
  ServicoIdRoute: typeof ServicoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/agenda': {
      id: '/painel/agenda'
      path: '/agenda'
      fullPath: '/painel/agenda'
      preLoaderRoute: typeof PainelAgendaRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/clientes': {
      id: '/painel/clientes'
      path: '/clientes'
      fullPath: '/painel/clientes'
      preLoaderRoute: typeof PainelClientesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/configuracoes': {
      id: '/painel/configuracoes'
      path: '/configuracoes'
      fullPath: '/painel/configuracoes'
      preLoaderRoute: typeof PainelConfiguracoesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/estoque': {
      id: '/painel/estoque'
      path: '/estoque'
      fullPath: '/painel/estoque'
      preLoaderRoute: typeof PainelEstoqueRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/financeiro': {
      id: '/painel/financeiro'
      path: '/financeiro'
      fullPath: '/painel/financeiro'
      preLoaderRoute: typeof PainelFinanceiroRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/galeria': {
      id: '/painel/galeria'
      path: '/galeria'
      fullPath: '/painel/galeria'
      preLoaderRoute: typeof PainelGaleriaRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/marketing': {
      id: '/painel/marketing'
      path: '/marketing'
      fullPath: '/painel/marketing'
      preLoaderRoute: typeof PainelMarketingRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/servicos': {
      id: '/painel/servicos'
      path: '/servicos'
      fullPath: '/painel/servicos'
      preLoaderRoute: typeof PainelServicosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/servico/$id': {
      id: '/servico/$id'
      path: '/servico/$id'
      fullPath: '/servico/$id'
      preLoaderRoute: typeof ServicoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PainelRouteChildren {
  PainelAgendaRoute: typeof PainelAgendaRoute
  PainelClientesRoute: typeof PainelClientesRoute
  PainelConfiguracoesRoute: typeof PainelConfiguracoesRoute
  PainelEstoqueRoute: typeof PainelEstoqueRoute
  PainelFinanceiroRoute: typeof PainelFinanceiroRoute
  PainelGaleriaRoute: typeof PainelGaleriaRoute
  PainelMarketingRoute: typeof PainelMarketingRoute
  PainelServicosRoute: typeof PainelServicosRoute
  PainelIndexRoute: typeof PainelIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelAgendaRoute: PainelAgendaRoute,
  PainelClientesRoute: PainelClientesRoute,
  PainelConfiguracoesRoute: PainelConfiguracoesRoute,
  PainelEstoqueRoute: PainelEstoqueRoute,
  PainelFinanceiroRoute: PainelFinanceiroRoute,
  PainelGaleriaRoute: PainelGaleriaRoute,
  PainelMarketingRoute: PainelMarketingRoute,
  PainelServicosRoute: PainelServicosRoute,
  PainelIndexRoute: PainelIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendarRoute: AgendarRoute,
  PainelRoute: PainelRouteWithChildren,
  ServicoIdRoute: ServicoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
